# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rm87056-checkpoint1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c1d7bec44ba749328d35fce528b77f6c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b7c85b2fbb3f431fa1124f486d300ec8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c1d7bec44ba749328d35fce528b77f6c }}/study:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rm87056-checkpoint1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bfe13a705f1b471b9e2df99129908bb2 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c1d7bec44ba749328d35fce528b77f6c }}/study:${{ github.sha }}'